version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: eduvial-backend
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_NAME=${POSTGRES_DB}
    volumes:
      - ./backend:/app
    networks:
      - eduvial-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: eduvial-frontend
    ports:
      - "8080:80"
    networks:
      - eduvial-net

  db:
    image: postgres:15
    container_name: eduvial-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: eduvial
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - eduvial-net

volumes:
  pgdata:

networks:
  eduvial-net:
