version: '3.8'

services:
  services:
  db:
    image: postgres:15
    container_name: eduvial-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: eduvial
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - eduvial-net

  backend:
    build:
      context: ./backend
    container_name: eduvial-backend
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=eduvial
    ports:
      - "3000:3000"
    networks:
      - eduvial-net

  frontend:
    build:
      context: ./frontend
    container_name: eduvial-frontend
    volumes:
      - ./frontend:/app
    tty: true
    networks:
      - eduvial-net

volumes:
  pgdata:

networks:
  eduvial-net:
