version: '3.8'

services:
  backend:
    build: .
    container_name: eduvial-backend
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=eduvial
    volumes:
      - .:/app
    networks:
      - eduvial-net

  db:
    image: postgres:15
    container_name: eduvial-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: eduvial
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - eduvial-net

volumes:
  pgdata:

networks:
  eduvial-net:
